# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# field.py
# Created on: 2015-01-17 19:27:58.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: field <CWS_GRID_Point> <Field_Name> <Expression> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
CWS_GRID_Point = arcpy.GetParameterAsText(0)
if CWS_GRID_Point == '#' or not CWS_GRID_Point:
    CWS_GRID_Point = "CWS_GRID_Point" # provide a default value if unspecified

Field_Name = arcpy.GetParameterAsText(1)
if Field_Name == '#' or not Field_Name:
    Field_Name = "Double" # provide a default value if unspecified

Expression = arcpy.GetParameterAsText(2)
if Expression == '#' or not Expression:
    Expression = "getDouble(Serial)" # provide a default value if unspecified

# Local variables:
CWS_GRID_Point__2_ = CWS_GRID_Point
Expression_Type = "PYTHON"
Code_Block = "def getDouble(field):\\n    return field*2"

# Process: Calculate Field
arcpy.CalculateField_management(CWS_GRID_Point, Field_Name, Expression, Expression_Type, Code_Block)

